title: Source Code Docs
description: Source Code Docs
theme: just-the-docs

url: https://ysj1173886760.github.io/source_code_docs/

# 导航配置
nav:
  - Home: index.md       # Link to your main docs index
  - DailyPaper: daily_paper/index.md
  - Graphiti: graphiti/index.md

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
